### ISSUE TITLE
Show progress on technical debt in our conformance progress page

### ISSUE THREAD

**Issue by zachmandeville** [apisnoop/snoopApp#10]
Both 'Stable Coverage At Time of Release' graphs should explicitly show the work done to reduce technical debt.  This is defined as new tests written for old endpoints.

On the graphs currently, tested shows as green and untested shows as red.  When a new endpoint comes in with a test it is shown as light green, and a new endpoint without a test a light yellow.

In addition, show tech debt progress with a different shade of green.

**Comment by riaankleinhans** [comment]
@zachmandeville
There was some debate about is "new_tested" a clear description, understandable to the general user.
It might read: (my thoughts)
New API's added with Conformance test
New API's added without Conformance test
Old API's getting Conformance tested
Conformance tested API's
Untested API's
