### ISSUE TITLE
Idea: Clicking on Release in conformance progress page brings you to its sunburst

### ISSUE THREAD

**Issue by zachmandeville** [apisnoop/snoopApp#11]
It would be cool to click on one of the bar charts in the conformance progress page and be brought to the details page of that release, with the sunburst and the list of new endpoints.

One thing to figure out with this: We have details for 1.15 and up, but the graphs start at 1.9.  Should 1.19 through 1.14 be clickable, and if so, where should they go?

**Comment by Riaankl** [comment]
@zachmandeville 
There was some debate about is "new_tested" is a clear description, understandable to the general user.
It might read: (my thoughts)
New API's added with Conformance test
New API's added without Conformance test
Old API's getting Conformance tested
Conformance tested API's
Untested API's

**Comment by hh** [comment]
The simplest would be just to have the list, sans the sunburst for releases we no longer have that data for.

Alternatively base the <1.15 sunbursts on endpoints from that release that still exist, and use master run data as the basis for those tests being hit. (similar to how the progress charts are generated).

However I think it's likely not worth the extra effort.
Just listing those newly introduced endpoint for each release is enough, as we primarily just want to see the technical debt enumberated.

**Comment by zachmandeville** [comment]
implemented in #14
