### ISSUE TITLE
Include Conformance Office Hours Meeting Notes and Writing good e2e tests for Kubernetes in the APISnoop About page

### ISSUE THREAD

**Issue by riaankleinhans** [apisnoop/snoopApp#24]
### Documentation improvement
Please add links to
 [Conformance Office Hours Meeting Notes](https://docs.google.com/document/d/1W31nXh9RYAb_VaYkwuPLd1hFxuRX3iU0DmaQ4lkCsX8/edit?pli=1#) in the **Additional Resources** section of the [About](https://apisnoop.cncf.io/about) page
[Writing good e2e tests for Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md)
in the **Additional Resources** section of the [About](https://apisnoop.cncf.io/about) page of APISnoop

**Comment by zachmandeville** [comment]
Updated in latest commit and live now at https://apisnoop.cncf.io/about
