### ISSUE TITLE
getInternalApiserverAPIGroup to be marked as "Not eligible for conformance yet"

### ISSUE THREAD

**Issue by riaankleinhans** [apisnoop/snoopApp#25]
The API Group [InternalApiserver ](https://apisnoop.cncf.io/1.20.0/alpha/internalApiserver) was added in 1.20 with sig-api-machinery [KEP ](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md) 
**getInternalApiserverAPIGroup** show as technical debt in 1.20. 
The endpoint must be move to Ineligible-endpoints marked as “No eligible for conformance yet”

**Comment by hh** [comment]
Let's ensure we engage on the KEP to include the requirement for conformance for promotion to GA with links back to APISnoop and the release blocking job.

**Comment by zachmandeville** [comment]
For this endpoint I am adding the following details. Do these sound right?

- endpoint :: getInternalApiserverAPIGroup
- reason :: 'Not eligible for conformance yet'
- sql logic :: endpoint = 'getInternalApiserverAPIGroup'
- link :: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190802-dynamic-coordinated-storage-version.md

**Comment by zachmandeville** [comment]
I've updated our eligible/ineligible lists to account for this endpoint and updated the json that snoopApp consumes.
You can see the change now on https://apisnoop.cncf.io/conformance-progress

If there are changes to be made to the reason or link, we can make these changes in another commit!
