### ISSUE TITLE
Documentation of updates required at on SnoopApp for every new release going live 

### ISSUE THREAD

**Issue by riaankleinhans** [apisnoop/snoopApp#27]
At the start of every K8s release the SnoopApp files constants.js and releases.yaml should be updated but the process and timing for it is not documents yet.

Please create a documented instruction for the process.

**Comment by zachmandeville** [comment]
This is now documented.  See https://github.com/apisnoop/snoopApp/blob/master/org/docs/updating-app-for-new-release.org
